### ISSUE TITLE
Gem not published?

### ISSUE THREAD

**Issue by OddEssay** [trailblazer/rspec-trailblazer#1]
Hi, love the idea of this gem, but when I try to include it as per the README with the usual `gem 'rspec-trailblazer'` line, it appears not to be a published gem.

I've checked both https://rubygems.org/search?utf8=%E2%9C%93&query=rspec-trailblazer and using the command line `gem search rspec-trailblazer`

Obviously, I can point directly to the GitHub repo. But it seems like you're expecting it to work via the Gemfile and it's maybe not showing up publicly.

**Comment by timoschilling** [comment]
Yes, this gem is not released and I'm not sure that this will happen in the future. I no longer like the idea. I make fullstack tests of my operations.

**Comment by OddEssay** [comment]
No problem, Thanks the heads up :)
