### ISSUE TITLE
Could not find gem 'rspec-trailblazer' in any of the gem sources listed in your Gemfile.

### ISSUE THREAD

**Issue by abhi4nfp** [trailblazer/rspec-trailblazer#3]
Added `gem 'rspec-trailblazer' ` to the Gemfile and then did `bundle`. this raises to the below error:

`Could not find gem 'rspec-trailblazer' in any of the gem sources listed in your Gemfile.`

**Comment by sarevalo** [comment]
You can try 

`gem 'rspec-trailblazer', :git => 'git@github.com:trailblazer/rspec-trailblazer.git'`

**Comment by abhi4nfp** [comment]
Thanks!
